# Generated by Buildr 1.4.5, change to your liking


# Version number for this release
VERSION_NUMBER = "0.1.0"
# Group identifier for your projects
GROUP = "pebbler"
COPYRIGHT = ""

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://www.ibiblio.org/maven2/"
repositories.remote << 'http://repo1.maven.org/maven2'

desc "The Pebbler project"
define "pebbler" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT
  # compile.with 'com.google.guava:guava:jar:10.0.1'
  compile.with 'com.google.code.gson:gson:jar:2.1'
  compile.options.lint = 'all'
  resources.from _('src/main/resources')
  package(:jar).with :manifest=>{
    'Copyright'=>'Josh Hoak, 2011',
    'Main-Class'=>'pebbler.StartPebbler'
  }
  package(:jar).merge('deps/gson-2.2.1.jar')

end

